name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'  # runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### optional customizations below:
          ### SHOW_TITLE: true
          ### BLOCKS: true
          ### TIME_RANGE: last_7_days
          ### LANG_COUNT: 5
